### ISSUE TITLE
Hyprland-autoname-workspaces and AGS

### ISSUE THREAD

**Issue by ArtemChandragupta** [agryphus/archrice#1]
Hi! I am trying to rewrite my waybar with AGS in order to understand it. 
![image](https://github.com/user-attachments/assets/4f1b27ac-3c1d-42e8-9f02-81354175bed7)
All modules are good except workspaces, which I am struggling to implement. Waybar module is handled by waybars built-in workspace autoname, which is similar to hyprland-autoname-workspaces. I tried to implement this module by myself using h-a-w and by nushell-scripts (extremely resourse-intensive), had no succes, so tried to find some examples. Yours is the only one on github, so I copied [this](https://github.com/agryphus/nixrice/blob/948cc33549d64065d7d91724de153ebf330635e1/misc/.config/ags/modules/bar/workspaces.js).

But I encountered some issues (mainly same that was then I modified default config to support h-a-w) :
1) Element updates only on creation of new workspace or some type of manipulation with clients(browser tab switching, terminal commands and moving in Yazi do so, using software manager not.)
2) As you can see, there is some flickering. Definitively a problem with classnames and style.css

https://github.com/user-attachments/assets/b0a8913b-3169-4cb4-a6de-aa09bc74a657

Have you encountered this issues? Can you help meto resolve them? I would be happy to get any reply.

Code that I have:

```js
const Hyprland = await Service.import("hyprland");

var monitorsActiveWorkspaceCache = new Array(10).fill(-1);

const is_active = (workspaceID) => {
  let monitorID = Hyprland.getWorkspace(workspaceID).monitorID;
  var monitor = Hyprland.getMonitor(monitorID);

  let activeID = -1;
  if (monitor == undefined) {
    activeID = monitorsActiveWorkspaceCache[monitorID];
  } else {
    monitorsActiveWorkspaceCache[monitorID] = monitor.activeWorkspace.id;
    activeID = monitor.activeWorkspace.id;
  }
  return workspaceID == activeID;
}

export const WorkspacesModule = (monitorID) => Widget.Box({
  class_name: 'WorkspacesModule',
  children: Hyprland.bind('workspaces').transform(ws => {
    return ws
      .filter(({ id, name }) => {
        if (name == "special") {
          // Hyprland sometimes uses a special workspace, which 
          // wouldn't appear on the bar.
          return false;
        }

        // Only show the workspaces belonging to the monitor
        return Hyprland.getWorkspace(id).monitorID == monitorID;
      })
      .sort((a, b) => a.id - b.id) // Show in order of ID
      .map(({ id, name }) => Widget.Button({
        on_clicked: () => Hyprland.sendMessage(`dispatch workspace ${id}`),
        child: Widget.Label(`${name}`),
        class_name: Hyprland.active.workspace.bind('id')
          .transform(i => `WorkButton${is_active(id) ? 'focused' : ''}`),
      }));
  }),
});
```

```js
import { WorkspacesModule } from "./modules/workspace/main.js"

function Left(monitor) {
  return Widget.Box({
    spacing: 8,
    children: [
      WorkspacesModule(monitor),
    ],
  })
}

const hyprlandMonitors = Utils.exec(`/bin/sh -c "hyprctl monitors | grep -o '(ID [0-9]*' | awk '{print $2}' | sort"`).split('\n').map(Number);

const getHyprlandMonitor = monitor => {
  if (monitor >= hyprlandMonitors.length) {
    return 0;
  }
  return hyprlandMonitors[monitor];
};

export function Bar(monitor = 0) {
  return Widget.Window({
    name: `bar-${monitor}`,
    class_name: "bar",
    monitor,
    anchor: ["top", "left", "right"],
    exclusivity: "exclusive",
    margins: [5, 10, -5, 10],
    child: Widget.CenterBox({
      start_widget: Left(getHyprlandMonitor(monitor)),
      center_widget: Center(),
      end_widget: Right(),
    }),
  })
}
```

```css
* {
    font-family: "JetBrainsMono Nerd Font, sans-serif";
    font-size: 14px;
}

window .bar {
    background: transparent;
    color: @theme_fg_color;
}


.FlakeModule {
    background: #282828;
    color: #98971a;
    font-size: 23px;
    padding: 1px 1px 1px 5px;
    margin: 0px;
    border-radius: 12px;
}
.TrayModule {
    background: #282828;
    padding: 0 10px;
    border-radius: 12px;
    margin: 0;
}
.TrayButtons {
    background: #282828;
    margin: 0;
    padding: 0 5px;
}
.WorkspacesModule {
    background: #282828;
    padding: 0 10px;
    border-radius: 12px;
    margin: 0;
}
.WorkButton {
    padding: 0 5px;
    background: #282828;
    border-radius: 0px;
}

.WorkButtonhover{
    background: #666666;
    padding: 0 5px;
}

.WorkButtonfocused{
    padding: 0 5px;
    color: #D79921;
}

.WorkButtonactive{
    color: #cc241d;
    padding: 0 5px;
}
```
